### ISSUE TITLE
Setup of pi-suite on pi zero w with Raspbian Jessie

### ISSUE THREAD

**Issue by ralle12345** [reelyactive/pi-suite#1]
I'm trying to setup pi-suite on my pi zero w as described [here](https://reelyactive.github.io/make-a-pi-hub.html). At first installation failed on bluetooth-hci-socket which bailed out with some permission problems during installation. It seemed --unsafe-perm fixed the problem, but in the end something seems missing. When starting pi-suite it fails with this error:

```
root@pizero:~/reelyActive/pi-suite# node ra-mqtt.js
reelyActive Barnacles instance is notifying an open IoT
reelyActive BarnOwl instance is listening for an open IoT
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/reelyActive/pi-suite/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Can you please help me debug this issue?

**Comment by jeffyactive** [comment]
Hi @ralle12345, the bluetooth-hci-socket package can be tricky to install/build.  Suggest you read the documentation and issues for that package specifically.  @sandeepmistry who maintains that package is usually quite active on the issues supporting various hardware.

If you make a breakthrough, please share and we'll be happy to update the tutorial for other Pi Zero users.  Thanks!

**Comment by ralle12345** [comment]
i found the missing file at /usr/local/node/lib/node_modules/bluetooth-hci-socket/build/Release/binding.node (where /usr/local/node is the location node.ja is installed under). After copying build/Release/binding.node to node_modules/bluetooth-hci-socket/ everything starts just as expected.
