### ISSUE TITLE
Error start pi-suite-hci.service

### ISSUE THREAD

**Issue by xianve** [reelyactive/pi-suite#7]
Environment Raspberry Pi 4B
Fresh install of Raspberry OS Lite

Clone and ran pi-suite from the command-line: sudo npm run start-hci
It works fine.

However once I add the service to systemd, it fails to start:
![image](https://user-images.githubusercontent.com/404900/102558092-8ddd9500-4081-11eb-990b-405fbb6f7762.png)

Assume it is something with permissions?

**Comment by xianve** [comment]
Not, removed the User=pi from the pi-suite-hci.service file, and re-installed it.
Now it works.

**Comment by jeffyactive** [comment]
Thanks @xianve for sharing the fix.  The User=pi line has been removed from pi-suite-hci.service so that it should run correctly as root or a user with the correct permissions as you indicated.
